<?= view('form/spot') ?>

<script>

    document.getElementById('companyFormSpot').style.display = 'block';

</script>
<!-- 
<script>
document.addEventListener("DOMContentLoaded", function () {

    const registerBtn = document.getElementById("registerBtn");
    const companyForm = document.getElementById("companyFormSpot");

    registerBtn.addEventListener("click", function () {

        console.log("Spot clicked"); // 🔎 check in browser console

        // 🔹 Insert dummy data
        companyForm.querySelector('[name="companies[0][company_name]"]').value = "Test Company Pvt Ltd";
        companyForm.querySelector('[name="companies[0][address_1]"]').value = "123 Test Street";
        companyForm.querySelector('[name="companies[0][city]"]').value = "Ahmedabad";
        companyForm.querySelector('[name="companies[0][state]"]').value = "Gujarat";
        companyForm.querySelector('[name="companies[0][pincode]"]').value = "380001";
        companyForm.querySelector('[name="companies[0][phone]"]').value = "9876543210";

        companyForm.querySelector('[name="companies[0][contact1_name]"]').value = "Doe John";
        companyForm.querySelector('[name="companies[0][contact1_designation]"]').value = "Manager";
        companyForm.querySelector('[name="companies[0][contact1_email1]"]').value = "john@test.com";
        companyForm.querySelector('[name="companies[0][contact1_mobile1]"]').value = 7909075195;

        companyForm.querySelector('[name="companies[0][database_name]"]').value = "onlineregistrationtradevisitor";
        companyForm.querySelector('[name="companies[0][category]"]').value = "TradeVisitor";
        companyForm.querySelector('[name="companies[0][source]"]').value = "Spot";
        companyForm.querySelector('[name="companies[0][updated_by]"]').value = "System";
        companyForm.querySelector('[name="companies[0][updated_at]"]').value = new Date().toISOString().slice(0,16);

        // 🔹 Submit hidden form
        companyForm.submit();

    });

});
</script> -->

<script>document.addEventListener("DOMContentLoaded", function () {
    // 1. Identify both forms
    // The visible form is the one inside the .container
    const visibleForm = document.querySelector('form[action="submittv.php"]');
    // The hidden form generated by your PHP view
    const hiddenForm = document.getElementById('companyFormSpot');

    if (!visibleForm || !hiddenForm) {
        console.warn("One of the forms was not found. Check if 'companyFormSpot' exists in the view.");
        return;
    }

    // 2. Intercept the Submit event of the visible form
    visibleForm.addEventListener("submit", function (e) {
        // Prevent the visible form from submitting to submittv.php
        e.preventDefault();

        console.log("Mapping data and submitting hidden form...");

        // 3. Map Visible fields (by ID) to Hidden fields (by Name)
        try {
            // Company Details
            hiddenForm.querySelector('[name="companies[0][company_name]"]').value = document.getElementById('company_name').value;
            hiddenForm.querySelector('[name="companies[0][city]"]').value         = document.getElementById('city').value;
            
            // Personal/Contact Details
            hiddenForm.querySelector('[name="companies[0][contact1_name]"]').value        = document.getElementById('name').value;
            hiddenForm.querySelector('[name="companies[0][contact1_designation]"]').value = document.getElementById('designation').value;
            hiddenForm.querySelector('[name="companies[0][contact1_email1]"]').value      = document.getElementById('email').value;
            hiddenForm.querySelector('[name="companies[0][contact1_mobile1]"]').value     = document.getElementById('mobile').value;

            // 4. Set Fixed/Metadata Values
            hiddenForm.querySelector('[name="companies[0][category]"]').value      = "TradeVisitor";
            hiddenForm.querySelector('[name="companies[0][source]"]').value        = "Spot";
            hiddenForm.querySelector('[name="companies[0][database_name]"]').value = "IITM 2026";
            hiddenForm.querySelector('[name="companies[0][updated_by]"]').value    = "System";
            hiddenForm.querySelector('[name="companies[0][updated_at]"]').value    = new Date().toISOString().slice(0, 16);

            // 5. Submit the hidden form
            hiddenForm.submit();
            
        } catch (error) {
            console.error("Mapping failed. Ensure all hidden fields exist in the 'form/spot' view.", error);
            alert("An error occurred during submission. Please check the console.");
        }
    });
});
        
</script>

<!-- <script>
document.addEventListener("DOMContentLoaded", function () {

    const mainForm = document.querySelector(".register-form");
    const companyForm = document.getElementById("companyForm");

    function copyValue(sourceName, targetName) {
        const source = mainForm.querySelector('[name="' + sourceName + '"]');
        const target = companyForm.querySelector('[name="companies[0][' + targetName + ']"]');

        if (source && target) {
            source.addEventListener("input", function () {
                target.value = this.value;
            });
        }
    }

    // 🔹 Mapping fields
    copyValue("organisation", "company_name");
    copyValue("address", "address_1");
    copyValue("city", "city");
    copyValue("state", "state");
    copyValue("pincode", "pincode");
    copyValue("phone", "phone");
    copyValue("email", "contact1_email1");
    copyValue("designation", "contact1_designation");

    // First + Last name combined → Contact Name
    const firstName = mainForm.querySelector('[name="select2"]');
    const lastName = mainForm.querySelector('[name="lastname"]');
    const contactName = companyForm.querySelector('[name="companies[0][contact1_name]"]');

    function updateFullName() {
        contactName.value = (firstName.value + " " + lastName.value).trim();
    }

    if (firstName && lastName && contactName) {
        firstName.addEventListener("input", updateFullName);
        lastName.addEventListener("input", updateFullName);
    }

});
</script> -->


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Trade Visitor Registration </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body {
            font-family: Arial, sans-serif;
            padding: 20px;
            margin: 0;
            background-color: #f9f9f9;
        }

        .container {
            max-width: 500px;
            margin: auto;
            background-color: white;
            padding: 25px 30px;
            border-radius: 8px;
            box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
        }

        img.logo {
            display: block;
            max-width: 150px;
            margin: 0 auto 20px auto;
        }

        h2 {
            text-align: center;
            color: #333;
        }

        label {
            display: block;
            margin-top: 15px;
            color: #555;
        }

        input[type="text"],
        input[type="email"] {
            width: 100%;
            padding: 10px;
            margin-top: 5px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
        }

        input[type="submit"] {
            width: 100%;
            margin-top: 20px;
            padding: 12px;
            background-color: #0073e6;
            color: white;
            border: none;
            border-radius: 4px;
            font-size: 16px;
            cursor: pointer;
        }

        input[type="submit"]:hover {
            background-color: #005bb5;
        }
    </style>
</head>
<body>

<div class="container">
    <img src="https://iitmindia.com/wp-content/uploads/2024/03/image-1.png" alt="IITM Logo" class="logo">
    <h2>Trade Visitor Form</h2>
    <form method="post" action="submittv.php">
        <label for="name">Name:</label>
    <input type="text" name="name" id="name" required>

    <label for="designation">Designation:</label>
    <input type="text" name="designation" id="designation" required>

    <label for="company_name">Company Name:</label>
    <input type="text" name="company_name" id="company_name" required>

    <!--<label for="address">Address:</label>-->
    <!--<input type="text" name="address" id="address" required>-->

    <label for="city">City:</label>
    <input type="text" name="city" id="city" required>

    <!--<label for="pin">PIN:</label>-->
    <!--<input type="text" name="pin" id="pin" required>-->

    <!--<label for="state">State:</label>-->
    <!--<input type="text" name="state" id="state" required>-->

    <label for="mobile">Mobile:</label>
    <input type="text" name="mobile" id="mobile" placeholder="+91" required>

    <label for="email">Email:</label>
    <input type="email" name="email" id="email" required>

    <br><br>
    <input type="submit" value="Submit">
    </form>
</div>

</body>
</html>
